# DataSource
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
spring.datasource.sql-script-encoding=UTF-8
spring.datasource.initialization-mode=always
spring.datasource.schema=classpath:schema.sql
spring.datasource.data=classpath:data.sql

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# セッション
server.servlet.session.persistent=false

# H2DB
#spring.h2.console.enabled=true
#spring.h2.console.settings.web-allow-others=true

spring.autoconfigure.exclude=\org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration

# message
spring.messages.basename=i18n/messages,i18n/ValidationMessages

# MyBatis
mybatis.mapper-locations=classpath:/mapper/h2/*.xml
#このプロパティをtrueにすると、select結果のアンダースコアをキャメル
#ケースに変更する(例user_id→userId)
mybatis.configuration.map-underscore-to-camel-case=true

#ここはデータ型のパッケージの指定
#こうする事でxml側のresultTypeでのパッケージ名を省略できる
mybatis.type-aliases-package=com.example.domain.user.model

# Log Level
logging.level.com.example=DEBUG
logging.level.root=DEBUG
debug=true

logging.level.org.springframework=DEBUG
logging.level.org.apache.catalina=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

# =================
# JPA
# =================
# テーブル自動作成
#spring.jpa.hibernate.ddl-auto=none
# SQLログ出力
#logging.level.org.hibernate.SQL=debug
# バインドパラメーター出力
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
#logging.level.org.hibernate.type.EnumType=trace

# サーバ用
#server.port=${PORT:10000}
